# Libraries import

In [1]:
# Core libraries
import numpy as np
import pandas as pd
import scanpy as sc
import anndata as ad
from pathlib import Path
from typing import Optional, Literal
from typing import Dict, Tuple, List
# Visualization
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.sparse as sp
import subprocess
# Integration methods
import harmonypy as hm  # Harmony integration
# Quality control
import scrublet  # Doublet detection
import sys
import io
import logging
# Utilities 
import warnings
warnings.filterwarnings('ignore')

# Set display options
sc.settings.verbosity = 3  # verbosity: errors (0), warnings (1), info (2), hints (3)
sc.settings.set_figure_params(dpi=100, facecolor='white')
import torch
torch.set_float32_matmul_precision("high")

/data1/esraa/miniconda3/envs/thesis-env/lib/python3.10/site-packages/louvain/__init__.py:54: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound

# Dataset01: GSE149614

In [3]:
# read data (normalized log1p data + full gene panel)
post_norm_dir = Path("/data1/esraa/Thesis-Project/Data/Processed_data/post_norm_log1p")
adata1 = sc.read_h5ad(post_norm_dir / "adata_149614.h5ad")

In [5]:
print(adata1.shape)  # Check the shape of the data

(66668, 25712)

In [5]:
import scanpy as sc

# adata = sc.read_h5ad("PATH/TO/METRICS_INPUT.h5ad")

# keep only a few obs columns (edit names to match yours)
keep_obs = [c for c in ["pseudotime", "group", "cell_type", "leiden"] if c in adata.obs.columns]

# keep a small gene subset (add your marker genes list here)
marker_genes = ["LYZ","S100A8","S100A9","FCGR3A","MARCO","TREM2","APOE","VEGFA","MKI67"]
keep_genes = [g for g in marker_genes if g in adata.var_names]

mini = adata[:, keep_genes].copy()
mini.obs = mini.obs[keep_obs]
mini.write("mini_metrics_check.h5ad")
print("wrote mini_metrics_check.h5ad with shape", mini.shape)

wrote mini_metrics_check.h5ad with shape (13496, 7)

In [ ]:
# check the column names of the data
print(adata1.obs.columns['patient'])

Index(['sample', 'res.3', 'site', 'patient', 'stage', 'virus', 'celltype',
       'dataset', 'cluster_annotation', 'NL', 'PT', 'PVTT', 'MLN',
       'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt',
       'total_counts_ribo', 'pct_counts_ribo', 'n_genes', 'n_counts',
       'donor_id', 'donor_resolution', 'technology', 'platform', 'sequencer',
       'source_repository', 'compartment', 'tissue', 'tumor_status',
       'disease_status', 'cancer_type', 'disease_group', 'cell_type_raw',
       'celltype_original', 'celltype_l0', 'celltype_l1', 'celltype_l2',
       'is_unclassified', 'is_cycling', 'valid_for_benchmark'],
      dtype='object')

In [ ]:
import pandas as pd

cluster_key = "cluster_annotation"
patient_key = "patient"

# Contingency table
ct = pd.crosstab( 
    adata1.obs[cluster_key],
    adata1.obs[patient_key]
)

# Raw counts
print("Raw cell counts per cluster per patient:")
display(ct)

# Row-normalized (proportion per cluster)
ct_prop = ct.div(ct.sum(axis=1), axis=0)

print("\nProportion of each patient within each cluster:")
display(ct_prop.round(3))

Raw cell counts per cluster per patient:

patient,HCC01,HCC02,HCC03,HCC04,HCC05,HCC06,HCC07,HCC08,HCC09,HCC10
cluster_annotation,,,,,,,,,,
ACTA2+ fibroblast,164,0,16,59,163,475,25,44,61,52
CD1C+ conventional dendritic cell,96,52,269,358,136,333,306,91,204,203
COL1A1+ fibroblast,18,13,15,97,27,176,79,457,148,106
FABP4+ endothelial,382,0,96,163,501,597,67,72,130,103
FCN3+ endothelial,16,0,112,309,336,137,111,71,32,41
IRF4+ plasmacytoid dendritic cell,1,0,12,5,9,17,24,15,21,11
MARCO+ macrophage,39,4,465,206,510,605,377,85,35,99
MMP9+ macrophage,19,16,34,65,4,38,213,635,57,354
SPARC+ endothelial,15,14,27,30,1,13,16,81,33,30
TREM2+ macrophage,211,6,180,450,30,376,234,269,169,245
VEGFA+ macrophage,825,0,81,106,12,84,90,56,86,195
central memory T,45,3,28,40,9,342,70,129,119,252
cholangiocyte,0,3,52,16,48,62,13,17,91,35
cytotoxic T lymphocytes,52,58,41,84,475,936,418,1048,164,427
effector memory T,54,8,19,51,475,305,269,400,5,415
intermediate T,67,14,80,34,280,601,210,454,38,238
mastocyte,1,0,1,1,1,19,0,5,26,7
mature B cell,2,190,17,19,28,295,31,15,24,156
monocyte-derived macrophage,279,6,211,159,66,311,755,702,157,491
mucosal-associated invariant T,159,10,26,571,652,418,499,568,18,361
naïve T,54,4,6,18,179,170,207,329,425,224
natural killer cell,440,87,184,549,928,792,724,1355,402,842
non-malignant hepatocyte,6,58,653,52,29,176,36,40,28,35
patient-specific macropahge,7,391,732,92,1035,48,137,20,3,31
plasma B cell,8,819,169,177,227,325,350,219,300,168
pro-metastatic hepatocyte,29,106,1376,1211,40,67,116,3343,1023,1884
pro-tumorigenic hepatocyte,13,1605,1988,382,885,82,65,367,273,360
proliferative CD4 T,37,26,151,81,93,107,75,156,97,148
proliferative CD8 T,1,113,7,0,2,0,1,2,1,1
proliferative macrophage,9,5,37,16,7,13,86,35,10,80
regulatory T,27,18,29,124,55,208,121,771,256,469
tissue-resident memory T,93,19,20,124,395,458,212,386,40,131

Proportion of each patient within each cluster:

patient,HCC01,HCC02,HCC03,HCC04,HCC05,HCC06,HCC07,HCC08,HCC09,HCC10
cluster_annotation,,,,,,,,,,
ACTA2+ fibroblast,0.155,0.000,0.015,0.056,0.154,0.449,0.024,0.042,0.058,0.049
CD1C+ conventional dendritic cell,0.047,0.025,0.131,0.175,0.066,0.163,0.149,0.044,0.100,0.099
COL1A1+ fibroblast,0.016,0.011,0.013,0.085,0.024,0.155,0.070,0.402,0.130,0.093
FABP4+ endothelial,0.181,0.000,0.045,0.077,0.237,0.283,0.032,0.034,0.062,0.049
FCN3+ endothelial,0.014,0.000,0.096,0.265,0.288,0.118,0.095,0.061,0.027,0.035
IRF4+ plasmacytoid dendritic cell,0.009,0.000,0.104,0.043,0.078,0.148,0.209,0.130,0.183,0.096
MARCO+ macrophage,0.016,0.002,0.192,0.085,0.210,0.249,0.155,0.035,0.014,0.041
MMP9+ macrophage,0.013,0.011,0.024,0.045,0.003,0.026,0.148,0.443,0.040,0.247
SPARC+ endothelial,0.058,0.054,0.104,0.115,0.004,0.050,0.062,0.312,0.127,0.115
TREM2+ macrophage,0.097,0.003,0.083,0.207,0.014,0.173,0.108,0.124,0.078,0.113
VEGFA+ macrophage,0.537,0.000,0.053,0.069,0.008,0.055,0.059,0.036,0.056,0.127
central memory T,0.043,0.003,0.027,0.039,0.009,0.330,0.068,0.124,0.115,0.243
cholangiocyte,0.000,0.009,0.154,0.047,0.142,0.184,0.039,0.050,0.270,0.104
cytotoxic T lymphocytes,0.014,0.016,0.011,0.023,0.128,0.253,0.113,0.283,0.044,0.115
effector memory T,0.027,0.004,0.009,0.025,0.237,0.152,0.134,0.200,0.002,0.207
intermediate T,0.033,0.007,0.040,0.017,0.139,0.298,0.104,0.225,0.019,0.118
mastocyte,0.016,0.000,0.016,0.016,0.016,0.311,0.000,0.082,0.426,0.115
mature B cell,0.003,0.245,0.022,0.024,0.036,0.380,0.040,0.019,0.031,0.201
monocyte-derived macrophage,0.089,0.002,0.067,0.051,0.021,0.099,0.241,0.224,0.050,0.157
mucosal-associated invariant T,0.048,0.003,0.008,0.174,0.199,0.127,0.152,0.173,0.005,0.110
naïve T,0.033,0.002,0.004,0.011,0.111,0.105,0.128,0.204,0.263,0.139
natural killer cell,0.070,0.014,0.029,0.087,0.147,0.126,0.115,0.215,0.064,0.134
non-malignant hepatocyte,0.005,0.052,0.587,0.047,0.026,0.158,0.032,0.036,0.025,0.031
patient-specific macropahge,0.003,0.157,0.293,0.037,0.415,0.019,0.055,0.008,0.001,0.012
plasma B cell,0.003,0.297,0.061,0.064,0.082,0.118,0.127,0.079,0.109,0.061
pro-metastatic hepatocyte,0.003,0.012,0.150,0.132,0.004,0.007,0.013,0.364,0.111,0.205
pro-tumorigenic hepatocyte,0.002,0.267,0.330,0.063,0.147,0.014,0.011,0.061,0.045,0.060
proliferative CD4 T,0.038,0.027,0.156,0.083,0.096,0.110,0.077,0.161,0.100,0.152
proliferative CD8 T,0.008,0.883,0.055,0.000,0.016,0.000,0.008,0.016,0.008,0.008
proliferative macrophage,0.030,0.017,0.124,0.054,0.023,0.044,0.289,0.117,0.034,0.268
regulatory T,0.013,0.009,0.014,0.060,0.026,0.100,0.058,0.371,0.123,0.226
tissue-resident memory T,0.050,0.010,0.011,0.066,0.210,0.244,0.113,0.206,0.021,0.070

In [4]:
print(adata1.obs["cluster_annotation"].value_counts())

cluster_annotation
pro-metastatic hepatocyte            9195
natural killer cell                  6303
pro-tumorigenic hepatocyte           6020
cytotoxic T lymphocytes              3703
mucosal-associated invariant T       3282
monocyte-derived macrophage          3137
plasma B cell                        2762
patient-specific macropahge          2496
MARCO+ macrophage                    2425
TREM2+ macrophage                    2170
FABP4+ endothelial                   2111
regulatory T                         2078
CD1C+ conventional dendritic cell    2048
intermediate T                       2016
effector memory T                    2001
tissue-resident memory T             1878
naïve T                              1616
VEGFA+ macrophage                    1535
MMP9+ macrophage                     1435
FCN3+ endothelial                    1165
COL1A1+ fibroblast                   1136
non-malignant hepatocyte             1113
ACTA2+ fibroblast                    1059
central memory T                     1037
proliferative CD4 T                   971
mature B cell                         777
cholangiocyte                         337
proliferative macrophage              298
SPARC+ endothelial                    260
proliferative CD8 T                   128
IRF4+ plasmacytoid dendritic cell     115
mastocyte                              61
Name: count, dtype: int64

In [ ]:
sc.pp.scale(adata1)  # rescale to 0 mean and variance of 1
_ = plt.hist(np.sum(adata1.X, axis=0), bins=100)
plt.xlabel("Mean of transcript totals")
plt.ylabel("Counts")
_ = plt.title("Dynamic range of transcripts in the data")

In [ ]:
sc.tl.pca(adata1, svd_solver="arpack")  # since neighbors() uses PCA values, compute them explicitly here
sc.pp.neighbors(adata1, n_neighbors=4, n_pcs=20)  # compute the kNN distances

In [ ]:
sc.tl.draw_graph(adata1)  # compute the graph
sc.pl.draw_graph(adata1, color="paul15_clusters")  # display the graph

In [ ]:
sc.tl.leiden(adata1, resolution=1, flavor="igraph", n_iterations=2)  # leiden clustering
sc.pl.draw_graph(adata1, color=["leiden", "paul15_clusters"])  # display the graph

In [ ]:
sc.tl.paga(adata1, groups="leiden")
sc.pl.paga(adata1, color=["leiden", "paul15_clusters"])

In [ ]:
sc.tl.draw_graph(adata1, init_pos="paga")
sc.pl.draw_graph(adata1, color=["leiden", "paul15_clusters"], legend_loc="on data")
sc.pl.draw_graph(adata1, color=["Hba-a2", "Elane"])|

# Dataset02: GSE151530

In [13]:
# read data (normalized log1p data + full gene panel)
post_norm_dir = Path("/data1/esraa/Thesis-Project/Data/Processed_data/post_norm_log1p")
adata2 = sc.read_h5ad(post_norm_dir / "adata_151530.h5ad")

In [14]:
# print the columns and the shape of the data
print(adata2.obs.columns)  # Check the observation columns of the data
print(adata2.shape)  # Check the shape of the data

Index(['dataset', 'S_ID', 'Sample', 'Type', 'n_genes_by_counts',
       'total_counts', 'total_counts_mt', 'pct_counts_mt', 'total_counts_ribo',
       'pct_counts_ribo', 'n_genes', 'n_counts', 'log1p_n_genes_by_counts',
       'log1p_total_counts', 'pct_counts_in_top_50_genes',
       'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes',
       'pct_counts_in_top_500_genes', 'log1p_total_counts_mt', 'donor_id',
       'donor_resolution', 'technology', 'platform', 'sequencer',
       'source_repository', 'tissue', 'compartment', 'tumor_status',
       'disease_status', 'cancer_type', 'disease_group', 'cell_type_raw',
       'celltype_original', 'celltype_l0', 'celltype_l1', 'celltype_l2',
       'is_unclassified', 'is_cycling', 'valid_for_benchmark'],
      dtype='object')
(48360, 18667)

In [15]:
#print the unique cell types from column Type
print(adata2.obs["Type"].unique())

['T cells', 'B cells', 'TAMs', 'unclassified', 'Malignant cells', 'TECs', 'CAFs']
Categories (7, object): ['B cells', 'CAFs', 'Malignant cells', 'T cells', 'TAMs', 'TECs', 'unclassified']

# Dataset03: GSE115469

In [ ]:
# read data (normalized log1p data + full gene panel)
post_norm_dir = Path("/data1/esraa/Thesis-Project/Data/Processed_data/post_norm_log1p")
adata3 = sc.read_h5ad(post_norm_dir / "adata_115469.h5ad")

In [ ]:
# print the columns and the shape of the data
print(adata3.obs.columns)  # Check the observation columns of the data
print(adata3.shape)  # Check the shape of the data

Index(['dataset', 'Sample', 'Cell#', 'Cluster#', 'CellType',
       'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt',
       'total_counts_ribo', 'pct_counts_ribo', 'n_genes', 'n_counts',
       'log1p_n_genes_by_counts', 'log1p_total_counts',
       'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes',
       'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes',
       'log1p_total_counts_mt', 'donor_id', 'donor_resolution', 'technology',
       'platform', 'sequencer', 'source_repository', 'tissue', 'compartment',
       'tumor_status', 'disease_status', 'disease_group', 'cancer_type',
       'cell_type_raw', 'celltype_original', 'celltype_l0', 'celltype_l1',
       'celltype_l2', 'is_unclassified', 'is_cycling', 'valid_for_benchmark'],
      dtype='object')
(8346, 20007)

In [ ]:
#print the unique cell types from column Type
print(adata3.obs["CellType"].unique())

['Central_venous_LSECs', 'Cholangiocytes', 'Non-inflammatory_Macrophage', 'alpha-beta_T_Cells', 'Inflammatory_Macrophage', ..., 'Erythroid_Cells', 'Hepatocyte_2', 'Hepatocyte_3', 'Hepatocyte_1', 'Hepatocyte_4']
Length: 20
Categories (20, object): ['Central_venous_LSECs', 'Cholangiocytes', 'Erythroid_Cells', 'Hepatic_Stellate_Cells', ..., 'Portal_endothelial_Cells', 'alpha-beta_T_Cells', 'gamma-delta_T_Cells_1', 'gamma-delta_T_Cells_2']

# Dataset04: GSE125449

In [3]:
# read data (normalized log1p data + full gene panel)
post_norm_dir = Path("/data1/esraa/Thesis-Project/Data/Processed_data/post_norm_log1p")
adata4 = sc.read_h5ad(post_norm_dir / "adata_125449.h5ad")

# print the columns and the shape of the data
print(adata4.obs.columns)  # Check the observation columns of the data
print(adata4.shape)  # Check the shape of the data

Index(['Sample', 'Type', 'batch', 'dataset_concat', 'dataset',
       'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt',
       'total_counts_ribo', 'pct_counts_ribo', 'n_genes', 'n_counts',
       'donor_id', 'donor_resolution', 'technology', 'platform', 'sequencer',
       'source_repository', 'tissue', 'compartment', 'tumor_status',
       'disease_status', 'disease_group', 'cancer_type', 'cell_type_raw',
       'celltype_original', 'celltype_l0', 'celltype_l1', 'celltype_l2',
       'is_unclassified', 'is_cycling', 'valid_for_benchmark'],
      dtype='object')
(8263, 21324)

In [4]:
#print the unique cell types from column Type
print(adata4.obs["Type"].unique())

['CAF', 'TEC', 'T cell', 'B cell', 'TAM', 'unclassified', 'Malignant cell', 'HPC-like']
Categories (8, object): ['B cell', 'CAF', 'HPC-like', 'Malignant cell', 'T cell', 'TAM', 'TEC', 'unclassified']

# Dataset05: GSE140228

In [2]:
# read data (normalized log1p data + full gene panel)
post_norm_dir = Path("/data1/esraa/Thesis-Project/Data/Processed_data/post_norm_log1p")
adata5 = sc.read_h5ad(post_norm_dir / "adata_140228.h5ad")

# print the columns and the shape of the data
print(adata5.obs.columns)  # Check the observation columns of the data
print(adata5.shape)  # Check the shape of the data

Index(['Donor', 'Tissue', 'celltype_sub', 'Platform', 'celltype_global',
       'Sample', 'Histology', 'Tissue_sub', 'dataset', 'technology',
       'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt',
       'total_counts_ribo', 'pct_counts_ribo', 'log1p_n_genes_by_counts',
       'log1p_total_counts', 'pct_counts_in_top_50_genes',
       'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes',
       'pct_counts_in_top_500_genes', 'log1p_total_counts_mt', 'donor_id',
       'donor_resolution', 'platform', 'sequencer', 'source_repository',
       'compartment', 'tissue', 'tumor_status', 'disease_status',
       'cancer_type', 'disease_group', 'cell_type_raw', 'celltype_original',
       'celltype_l0', 'celltype_l1', 'celltype_l2', 'is_unclassified',
       'is_cycling', 'valid_for_benchmark'],
      dtype='object')
(64441, 54574)

In [8]:
# Print unique values as a pandas DataFrame
unique_celltypes = (
    pd.Series(adata5.obs["celltype_sub"].dropna().unique(), name="celltype_sub")
    .sort_values()
    .reset_index(drop=True)
)

# Print number of cells for each subtype
subtype_counts = (
    adata5.obs["celltype_sub"]
    .dropna()
    .value_counts()
    .rename_axis("celltype_sub")
    .reset_index(name="n_cells")
)

display(subtype_counts)

          celltype_sub  n_cells
0          CD8-C6-GZMK     8219
1          CD4-C5-TCF7     5283
2        CD8-C4-CX3CR1     3928
3         CD8-C7-KLRD1     3747
4           Lymphoid-B     3542
5      CD4/CD8-C1-CCR7     3418
6       CD8-C9-SLC4A10     3110
7          CD4-C4-IL7R     2737
8         CD4-C3-ANXA1     2674
9          NK-C7-CD160     2370
10         CD8-C5-SELL     2190
11        NK-C1-FCGR3A     2082
12          Mφ-C2-C1QA     1963
13          NK-C5-CD69     1898
14        CD4-C7-FOXP3     1879
15         Mφ-C6-MARCO     1536
16          DC-C1-CD1C     1453
17          Mφ-C5-VCAN     1232
18         Mφ-C1-THBS1     1225
19        CD8-C8-PDCD1     1199
20   Lymphoid-B-Plasma     1113
21         CD8-C3-IL7R      975
22       CD4-C6-CXCL13      750
23      Mono-C2-FCGR3A      730
24          NK-C3-IFNG      602
25        DC-C2-FCER1A      591
26   NK-C4-IFNG-HSPA1A      585
27  NK-C8-CD160-HSPA1A      448
28        DC-C3-CLEC9A      397
29    CD4/CD8-C2-MKI67      390
30        Mono-C1-CD14      284
31          NK-C2-SELL      283
32          Mφ-C3-APOE      260
33        Mast-C1-IL7R      244
34                ILCs      198
35          NK-C6-IL7R      197
36          Mφ-C4-GPX3      195
37         NK-C9-MKI67      186
38        Mast-C2-CPA3      164
39         DC-C4-LAMP3      164

## construct helper gene markers for the metrics evaluation